// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// convolution_table
DataFrame convolution_table(NumericVector capacity, NumericVector efor, double threshold);
RcppExport SEXP repra_convolution_table(SEXP capacitySEXP, SEXP eforSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type capacity(capacitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type efor(eforSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    __result = Rcpp::wrap(convolution_table(capacity, efor, threshold));
    return __result;
END_RCPP
}
