// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// convolution_table
DataFrame convolution_table(NumericVector capacity, NumericVector efor, double threshold);
RcppExport SEXP repra_convolution_table(SEXP capacitySEXP, SEXP eforSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type capacity(capacitySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type efor(eforSEXP );
        Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP );
        DataFrame __result = convolution_table(capacity, efor, threshold);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
