# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolution_table <- function(capacity, efor, threshold) {
    .Call('repra_convolution_table', PACKAGE = 'repra', capacity, efor, threshold)
}

